[build]
  command = "npm run build"
  functions = "netlify/functions/"
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@mailchimp/mailchimp_marketing"]
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200